name: Build & Test Main

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

env:
    NETCORE_VERSION: '6.0.x'
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    PROJECT_NAME: FluentValidation
    GITHUB_USER: liero
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NUGET_FEED: https://api.nuget.org/v3/index.json
    NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    #- name: Restore tools
    #  run: dotnet tool restore      
    #  working-directory: BlazorComponents

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore --verbosity normal
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: nugetpackage
        path: vNext.BlazorComponents.FluentValidation/bin/Release/*.nupkg

  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: nugetpackage
        
    - name: Publish to nuget
      run:  dotnet nuget push "**/vNext.BlazorComponents.*.nupkg" --skip-duplicate  -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
